name: Build et Test avec démarrage API

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Démarrer l'API en arrière-plan
        run: |
          uvicorn app:app --host 0.0.0.0 --port 8000 &
          sleep 5  # attends que le serveur démarre

      - name: Lancer les tests
        run: pytest tests/test_api.py