name: Build, Test et Deploy API Docker

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les dépendances
        run: pip install -r requirements.txt

      - name: Démarrer l'API en arrière-plan
        run: |
          uvicorn api.api:app --host 0.0.0.0 --port 8000 > server.log 2>&1 &
          sleep 15
          cat server.log

      - name: Lancer les tests (avec logs)
        run: pytest -s tests/test_api.py

      - name: Se connecter à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build et push l'image Docker
        run: |
          docker build -t ben8787/monprojetmlops:latest .
          docker push ben8787/monprojetmlops:latest

      - name: Déployer sur Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: monprojetmlops
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: 'ben8787/monprojetmlops:latest'